import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MaiL-BoX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        {/* <head>
        <link rel="icon" href="/favicon.ico" />
      </head> */}
        <body className={inter.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
